"""Realtime (WebSocket) contract constants for v1.1."""

SCHEMA_VERSION = 1


class WsErrorCode:
    INVALID_TOKEN = "INVALID_TOKEN"
    BAD_MESSAGE = "BAD_MESSAGE"
    NO_SESSION = "NO_SESSION"
    ALREADY_ACTIVE = "ALREADY_ACTIVE"
    UNSUPPORTED_EXERCISE = "UNSUPPORTED_EXERCISE"
    BAD_DIFFICULTY = "BAD_DIFFICULTY"
    START_FAILED = "START_FAILED"
    MODEL_MISSING = "MODEL_MISSING"
    BAD_FRAME = "BAD_FRAME"
