/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform Stats */
        get: operations["platform_stats_v1_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete User
         * @description Permanently remove a user and all their data (sessions, metrics, links).
         */
        delete: operations["delete_user_v1_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Role */
        patch: operations["change_role_v1_admin_users__user_id__role_patch"];
        trace?: never;
    };
    "/v1/analytics/exercise/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Exercise */
        get: operations["analytics_exercise_v1_analytics_exercise__exercise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Overview */
        get: operations["analytics_overview_v1_analytics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_v1_chat_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unread Count */
        get: operations["unread_count_v1_chat_unread_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/{partner_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Messages */
        get: operations["get_messages_v1_chat__partner_id__messages_get"];
        put?: never;
        /** Send Message */
        post: operations["send_message_v1_chat__partner_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_v1_exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_v1_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fatigue/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fatigue History */
        get: operations["fatigue_history_v1_fatigue_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fatigue/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict Fatigue */
        post: operations["predict_fatigue_v1_fatigue_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invite */
        post: operations["accept_invite_v1_invites_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/plan/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today Plan */
        get: operations["today_plan_v1_me_plan_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/trainers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Trainers
         * @description Client-side view: which trainers currently coach me.
         */
        get: operations["my_trainers_v1_me_trainers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Daily Report */
        get: operations["get_daily_report_v1_reports_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_v1_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Session */
        post: operations["end_session_v1_sessions__session_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Feedback */
        get: operations["get_session_feedback_v1_sessions__session_id__feedback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Session */
        post: operations["start_session_v1_sessions__session_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trainer/assignments/{assignment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel Assignment */
        delete: operations["cancel_assignment_v1_trainer_assignments__assignment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trainer/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_v1_trainer_clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trainer/clients/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Client Sessions
         * @description Which of my linked clients are in a live workout right now.
         */
        get: operations["live_client_sessions_v1_trainer_clients_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trainer/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** End Client Link */
        delete: operations["end_client_link_v1_trainer_clients__client_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trainer/clients/{client_id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Client Assignments */
        get: operations["client_assignments_v1_trainer_clients__client_id__assignments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trainer/clients/{client_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Client Sessions */
        get: operations["client_sessions_v1_trainer_clients__client_id__sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trainer/clients/{client_id}/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Client Session Detail
         * @description Full coaching breakdown of one client session.
         *
         *     Same shape as the client's own daily report entries: targets vs actual,
         *     volume load, the generated form review (top errors + action items), and
         *     aggregated per-rep quality stats (ROM, tempo, depth).
         */
        get: operations["client_session_detail_v1_trainer_clients__client_id__sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trainer/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invites */
        get: operations["list_invites_v1_trainer_invites_get"];
        put?: never;
        /** Create Invite */
        post: operations["create_invite_v1_trainer_invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trainer/invites/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invite */
        delete: operations["revoke_invite_v1_trainer_invites__invite_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trainer/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Programs */
        get: operations["list_programs_v1_trainer_programs_get"];
        put?: never;
        /** Create Program */
        post: operations["create_program_v1_trainer_programs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trainer/programs/{program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Program */
        delete: operations["delete_program_v1_trainer_programs__program_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trainer/programs/{program_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Program */
        post: operations["assign_program_v1_trainer_programs__program_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_users_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Me
         * @description Permanently delete the caller's own account and all data derived from it.
         *
         *     Google Play requires an in-app path to account deletion for any app that
         *     lets users create an account. Every table referencing ``users.id`` declares
         *     ON DELETE CASCADE (or SET NULL), so the database removes the dependent rows;
         *     the relationships use passive_deletes so SQLAlchemy does not try to NULL out
         *     NOT NULL foreign keys on the way.
         */
        delete: operations["delete_me_v1_users_me_delete"];
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_v1_users_me_patch"];
        trace?: never;
    };
    "/v1/users/me/body-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Body Metrics */
        get: operations["list_body_metrics_v1_users_me_body_metrics_get"];
        put?: never;
        /** Create Body Metric */
        post: operations["create_body_metric_v1_users_me_body_metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminStatsResponse */
        AdminStatsResponse: {
            /** Activecoachinglinks */
            activeCoachingLinks: number;
            /** Admins */
            admins: number;
            /** Clients */
            clients: number;
            /** Completedsessions */
            completedSessions: number;
            /** Pendinginvites */
            pendingInvites: number;
            /** Sessionslast7D */
            sessionsLast7d: number;
            /** Totalusers */
            totalUsers: number;
            /** Trainers */
            trainers: number;
        };
        /** AdminUserResponse */
        AdminUserResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Displayname */
            displayName: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
        };
        /** AnalyticsOverviewResponse */
        AnalyticsOverviewResponse: {
            /** Avgformscore */
            avgFormScore?: number | null;
            /** Completedsessions */
            completedSessions: number;
            /** Totalsessions */
            totalSessions: number;
        };
        /** AssignProgramRequest */
        AssignProgramRequest: {
            /**
             * Clientid
             * Format: uuid
             */
            clientId: string;
            /**
             * Startdate
             * @description YYYY-MM-DD; defaults to today
             */
            startDate?: string | null;
        };
        /** AssignmentResponse */
        AssignmentResponse: {
            /**
             * Clientid
             * Format: uuid
             */
            clientId: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Dayselapsed */
            daysElapsed?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Programid
             * Format: uuid
             */
            programId: string;
            /** Programname */
            programName: string;
            /**
             * Sessionscompleted
             * @default 0
             */
            sessionsCompleted: number;
            /**
             * Startdate
             * Format: date
             */
            startDate: string;
            /** Status */
            status: string;
        };
        /** BodyMetricCreateRequest */
        BodyMetricCreateRequest: {
            /** Bodyfatpercent */
            bodyFatPercent: number;
            /** Date */
            date: string;
            /** Weightkg */
            weightKg: number;
        };
        /** BodyMetricResponse */
        BodyMetricResponse: {
            /** Bodyfatpercent */
            bodyFatPercent: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Weightkg */
            weightKg: number;
        };
        /** ChatMessageResponse */
        ChatMessageResponse: {
            /** Body */
            body: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Readat */
            readAt?: string | null;
            /**
             * Recipientid
             * Format: uuid
             */
            recipientId: string;
            /**
             * Senderid
             * Format: uuid
             */
            senderId: string;
        };
        /** ChatSendRequest */
        ChatSendRequest: {
            /** Body */
            body: string;
        };
        /** ConversationResponse */
        ConversationResponse: {
            /** Lastat */
            lastAt?: string | null;
            /** Lastmessage */
            lastMessage?: string | null;
            /**
             * Partnerid
             * Format: uuid
             */
            partnerId: string;
            /** Partnername */
            partnerName: string;
            /** Partnerrole */
            partnerRole: string;
            /**
             * Unreadcount
             * @default 0
             */
            unreadCount: number;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Assignmentid */
            assignmentId?: string | null;
            /** Bodyweightkg */
            bodyWeightKg?: number | null;
            /**
             * Difficulty
             * @default intermediate
             */
            difficulty: string;
            /** Exerciseid */
            exerciseId: string;
            /** Externalloadkg */
            externalLoadKg?: number | null;
            /**
             * Targetreps
             * @default 1
             */
            targetReps: number;
            /**
             * Targetsets
             * @default 1
             */
            targetSets: number;
        };
        /** DailyReportResponse */
        DailyReportResponse: {
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Sessions */
            sessions: components["schemas"]["DailyReportSessionResponse"][];
            summary: components["schemas"]["DailyReportSummaryResponse"];
            user: components["schemas"]["ReportUserResponse"];
        };
        /** DailyReportSessionResponse */
        DailyReportSessionResponse: {
            /** Avgformscore */
            avgFormScore?: number | null;
            /** Bodyweightkg */
            bodyWeightKg?: number | null;
            /** Difficulty */
            difficulty: string;
            /** Durationseconds */
            durationSeconds?: number | null;
            /** Endedat */
            endedAt?: string | null;
            /** Estimatedvolumeloadkg */
            estimatedVolumeLoadKg?: number | null;
            /** Exerciseid */
            exerciseId: string;
            /** Exercisename */
            exerciseName: string;
            /** Externalloadkg */
            externalLoadKg?: number | null;
            feedback?: components["schemas"]["SessionFeedbackResponse"] | null;
            repStats: components["schemas"]["ReportRepStatsResponse"];
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            /** Startedat */
            startedAt?: string | null;
            /** Targetreps */
            targetReps: number;
            /** Targetsets */
            targetSets: number;
            /** Totalreps */
            totalReps: number;
            /** Usesexternalload */
            usesExternalLoad: boolean;
        };
        /** DailyReportSummaryResponse */
        DailyReportSummaryResponse: {
            /** Avgformscore */
            avgFormScore?: number | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Timezone */
            timezone: string;
            /** Totaldurationseconds */
            totalDurationSeconds: number;
            /**
             * Totalexternalloadvolumekg
             * @description Sum of externalLoadKg * reps for weighted rep-based workouts.
             */
            totalExternalLoadVolumeKg?: number | null;
            /** Totalreps */
            totalReps: number;
            /** Totalsessions */
            totalSessions: number;
        };
        /**
         * DeleteUserMeRequest
         * @description Re-authentication for permanent account deletion.
         *
         *     The current password is required so that an unlocked phone (or a stolen
         *     access token) is not enough to destroy the account irreversibly.
         */
        DeleteUserMeRequest: {
            /** Password */
            password: string;
        };
        /** EndSessionRequest */
        EndSessionRequest: {
            /** Avgformscore */
            avgFormScore?: number | null;
            /** Bodyweightkg */
            bodyWeightKg?: number | null;
            /** Externalloadkg */
            externalLoadKg?: number | null;
            /** Totalreps */
            totalReps?: number | null;
        };
        /** ExerciseResponse */
        ExerciseResponse: {
            /** Default Difficulty */
            default_difficulty: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ExplainabilityFactorResponse */
        ExplainabilityFactorResponse: {
            /** Detail */
            detail: string;
            /** Impact */
            impact: number;
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** FatiguePredictRequest */
        FatiguePredictRequest: {
            /** Exerciseid */
            exerciseId: string;
            /**
             * Recentwindowdays
             * @default 14
             */
            recentWindowDays: number;
            /**
             * Usercontext
             * @description Optional: sleepHours, muscleSoreness (1-5), stress (1-5), externalLoadKg, bodyWeightKg.
             */
            userContext?: {
                [key: string]: unknown;
            };
        };
        /** FatiguePredictResponse */
        FatiguePredictResponse: {
            /** Exerciseid */
            exerciseId: string;
            /** Explainability */
            explainability?: components["schemas"]["ExplainabilityFactorResponse"][];
            /** Factors */
            factors: string[];
            /** Fatiguelevel */
            fatigueLevel: string;
            /** Featuresnapshot */
            featureSnapshot?: {
                [key: string]: unknown;
            };
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Predictionid */
            predictionId?: string | null;
            /** Readinessscore */
            readinessScore: number;
            /** Recommendation */
            recommendation: string;
        };
        /** FeedbackActionItem */
        FeedbackActionItem: {
            /** Cue */
            cue: string;
            /** Howtofix */
            howToFix: string;
            /** Priority */
            priority: number;
            /** Title */
            title: string;
            /** Why */
            why: string;
        };
        /** FeedbackTopErrorItem */
        FeedbackTopErrorItem: {
            /** Code */
            code: string;
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Severity */
            severity: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InviteAcceptRequest */
        InviteAcceptRequest: {
            /** Token */
            token: string;
        };
        /** InviteAcceptResponse */
        InviteAcceptResponse: {
            /** Status */
            status: string;
            /**
             * Trainerid
             * Format: uuid
             */
            trainerId: string;
            /** Trainername */
            trainerName: string;
        };
        /** InviteCreateRequest */
        InviteCreateRequest: {
            /**
             * Email
             * @description Optional: restrict the invite to this email.
             */
            email?: string | null;
            /**
             * Expiresindays
             * @default 7
             */
            expiresInDays: number;
        };
        /** InviteResponse */
        InviteResponse: {
            /** Acceptedat */
            acceptedAt?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Email */
            email?: string | null;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Token */
            token: string;
        };
        /** LiveClientSessionResponse */
        LiveClientSessionResponse: {
            /**
             * Clientid
             * Format: uuid
             */
            clientId: string;
            /** Clientname */
            clientName: string;
            /** Exerciseid */
            exerciseId: string;
            /** Sessionid */
            sessionId: string;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
        };
        /** PlanExerciseResponse */
        PlanExerciseResponse: {
            /** Adjustedreps */
            adjustedReps: number;
            /** Adjustedsets */
            adjustedSets: number;
            /** Adjustmentnote */
            adjustmentNote?: string | null;
            /** Exerciseid */
            exerciseId: string;
            /** Exercisename */
            exerciseName: string;
            /** Externalloadkg */
            externalLoadKg?: number | null;
            /** Fatiguelevel */
            fatigueLevel: string;
            /** Notes */
            notes?: string | null;
            /** Prescribedreps */
            prescribedReps: number;
            /** Prescribedsets */
            prescribedSets: number;
            /** Readinessscore */
            readinessScore: number;
            /** Restseconds */
            restSeconds: number;
        };
        /** ProgramCreateRequest */
        ProgramCreateRequest: {
            /** Days */
            days?: components["schemas"]["ProgramDayInput"][];
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /**
             * Weeks
             * @default 1
             */
            weeks: number;
        };
        /** ProgramDayInput */
        ProgramDayInput: {
            /** Dayindex */
            dayIndex: number;
            /** Exercises */
            exercises?: components["schemas"]["ProgramExerciseInput"][];
            /** Notes */
            notes?: string | null;
        };
        /** ProgramDayResponse */
        ProgramDayResponse: {
            /** Dayindex */
            dayIndex: number;
            /** Exercises */
            exercises?: components["schemas"]["ProgramExerciseResponse"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes?: string | null;
        };
        /** ProgramExerciseInput */
        ProgramExerciseInput: {
            /** Exerciseid */
            exerciseId: string;
            /** Externalloadkg */
            externalLoadKg?: number | null;
            /** Notes */
            notes?: string | null;
            /**
             * Restseconds
             * @default 60
             */
            restSeconds: number;
            /**
             * Targetreps
             * @default 1
             */
            targetReps: number;
            /**
             * Targetsets
             * @default 1
             */
            targetSets: number;
        };
        /** ProgramExerciseResponse */
        ProgramExerciseResponse: {
            /** Exerciseid */
            exerciseId: string;
            /** Externalloadkg */
            externalLoadKg?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes?: string | null;
            /** Position */
            position: number;
            /** Restseconds */
            restSeconds: number;
            /** Targetreps */
            targetReps: number;
            /** Targetsets */
            targetSets: number;
        };
        /** ProgramResponse */
        ProgramResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Days */
            days?: components["schemas"]["ProgramDayResponse"][];
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Weeks */
            weeks: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default client
             */
            role: string;
        };
        /** ReportRepStatsResponse */
        ReportRepStatsResponse: {
            /** Avgformscore */
            avgFormScore?: number | null;
            /** Avgrangeofmotion */
            avgRangeOfMotion?: number | null;
            /** Avgrepdurationms */
            avgRepDurationMs?: number | null;
            /** Depthqualitycounts */
            depthQualityCounts?: {
                [key: string]: number;
            };
            /** Repcount */
            repCount: number;
        };
        /** ReportUserResponse */
        ReportUserResponse: {
            /** Displayname */
            displayName: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** SessionFeedbackResponse */
        SessionFeedbackResponse: {
            /** Actionitems */
            actionItems: components["schemas"]["FeedbackActionItem"][];
            /** Confidenceoverall */
            confidenceOverall: number | null;
            /** Errorbreakdown */
            errorBreakdown: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Errorscount */
            errorsCount: number;
            /** Exerciseid */
            exerciseId: string;
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Overallrating */
            overallRating: number;
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            /** Signalsused */
            signalsUsed: {
                [key: string]: unknown;
            };
            /** Summarytext */
            summaryText: string;
            /** Toperrors */
            topErrors: components["schemas"]["FeedbackTopErrorItem"][];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Version */
            version: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Avgformscore */
            avgFormScore?: number | null;
            /** Bodyweightkg */
            bodyWeightKg?: number | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Difficulty */
            difficulty: string;
            /** Durationseconds */
            durationSeconds?: number | null;
            /** Endedat */
            endedAt?: string | null;
            /** Exerciseid */
            exerciseId: string;
            /** Externalloadkg */
            externalLoadKg?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Startedat */
            startedAt?: string | null;
            /** Status */
            status: string;
            /** Targetreps */
            targetReps: number;
            /** Targetsets */
            targetSets: number;
            /** Totalreps */
            totalReps: number;
        };
        /** TodayPlanResponse */
        TodayPlanResponse: {
            /** Assignmentid */
            assignmentId?: string | null;
            /** Cyclelength */
            cycleLength?: number | null;
            /** Dayindex */
            dayIndex?: number | null;
            /** Daynotes */
            dayNotes?: string | null;
            /** Exercises */
            exercises?: components["schemas"]["PlanExerciseResponse"][];
            /** Hasplan */
            hasPlan: boolean;
            /** Message */
            message?: string | null;
            /** Programname */
            programName?: string | null;
            /**
             * Restday
             * @default false
             */
            restDay: boolean;
            /** Trainername */
            trainerName?: string | null;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TrainerClientResponse */
        TrainerClientResponse: {
            /**
             * Clientid
             * Format: uuid
             */
            clientId: string;
            /** Displayname */
            displayName: string;
            /** Email */
            email: string;
            /**
             * Linkedat
             * Format: date-time
             */
            linkedAt: string;
            /** Status */
            status: string;
        };
        /** UpdateRoleRequest */
        UpdateRoleRequest: {
            /** Role */
            role: string;
        };
        /** UpdateUserMeRequest */
        UpdateUserMeRequest: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Body Fat Percent */
            body_fat_percent?: number | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Locale */
            locale?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /** UserMeResponse */
        UserMeResponse: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Body Fat Percent */
            body_fat_percent?: number | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Height Cm */
            height_cm?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Locale */
            locale: string;
            /** Role */
            role: string;
            /** Timezone */
            timezone: string;
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    platform_stats_v1_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsResponse"];
                };
            };
        };
    };
    list_users_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserResponse"][];
                };
            };
        };
    };
    delete_user_v1_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_role_v1_admin_users__user_id__role_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_exercise_v1_analytics_exercise__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_overview_v1_analytics_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOverviewResponse"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_v1_chat_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"][];
                };
            };
        };
    };
    unread_count_v1_chat_unread_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    get_messages_v1_chat__partner_id__messages_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                partner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_v1_chat__partner_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partner_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exercises_v1_exercises_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"][];
                };
            };
        };
    };
    get_exercise_v1_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fatigue_history_v1_fatigue_history_get: {
        parameters: {
            query: {
                exerciseId: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FatiguePredictResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_fatigue_v1_fatigue_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FatiguePredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FatiguePredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    accept_invite_v1_invites_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteAcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteAcceptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    today_plan_v1_me_plan_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayPlanResponse"];
                };
            };
        };
    };
    my_trainers_v1_me_trainers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainerClientResponse"][];
                };
            };
        };
    };
    get_daily_report_v1_reports_daily_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_v1_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
        };
    };
    create_session_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_v1_sessions__session_id__end_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EndSessionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_feedback_v1_sessions__session_id__feedback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionFeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_v1_sessions__session_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_assignment_v1_trainer_assignments__assignment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_v1_trainer_clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainerClientResponse"][];
                };
            };
        };
    };
    live_client_sessions_v1_trainer_clients_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveClientSessionResponse"][];
                };
            };
        };
    };
    end_client_link_v1_trainer_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_assignments_v1_trainer_clients__client_id__assignments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_sessions_v1_trainer_clients__client_id__sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_session_detail_v1_trainer_clients__client_id__sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyReportSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invites_v1_trainer_invites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"][];
                };
            };
        };
    };
    create_invite_v1_trainer_invites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invite_v1_trainer_invites__invite_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_programs_v1_trainer_programs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramResponse"][];
                };
            };
        };
    };
    create_program_v1_trainer_programs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_program_v1_trainer_programs__program_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_program_v1_trainer_programs__program_id__assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignProgramRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
        };
    };
    delete_me_v1_users_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteUserMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_body_metrics_v1_users_me_body_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMetricResponse"][];
                };
            };
        };
    };
    create_body_metric_v1_users_me_body_metrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BodyMetricCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMetricResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
